apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: default
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 9000

# kubectl apply -f minio-external.yaml 
#   service/minio-external created
